name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          minikube docker-env --shell powershell | Invoke-Expression
          docker build -t train-ticket-app:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/